### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by pucedoteth**
i have update wormhole docs by added **Xpla** name so this will help to show their name. **(see pic)**. Also i edit the link which will lead directly to **token bridge**.

Screenshot 2023-11-08 at 1 23 17 AM

### CODE REVIEW

**Comment by barnjamin** [comment]
Thanks! 

The way the name `XPLA` name should be updated is to set the value here: https://github.com/wormhole-foundation/docs.wormhole.com/blob/main/scripts/src/chains/xpla.json#L2

Then run `npm run generate` in the `scripts` directory. Are you able to do that?

**Comment by pucedoteth** [comment]
> Thanks!
> 
> The way the name `XPLA` name should be updated is to set the value here: https://github.com/wormhole-foundation/docs.wormhole.com/blob/main/scripts/src/chains/xpla.json#L2
> 
> Then run `npm run generate` in the `scripts` directory. Are you able to do that?

could you name me the steps pls?

**Comment by barnjamin** [comment]
with repo cloned locally
1) `cd docs.wormhole.com/scripts`
2) `npm install`
3) modify the `xpla.json` file
4) `npm run generate`
5) git diff (check that it looks right)
6) git commit -am "regen docs with xpla"
7) git push

**Comment by pucedoteth** [comment]
> * git commit -am "regen docs with xpla"

could you check now its works thank you

**Comment by barnjamin** [comment]
hey @pucedoteth it looks like the process may not have been followed exactly, I'd expect to see more changes if the generate script was run (like this https://github.com/wormhole-foundation/docs.wormhole.com/blob/main/docs/reference/environments/README.md?plain=1#L193)

**Comment by barnjamin** [comment]
@pucedoteth I've made the change to the config file and done the regen in #149

**Pull request closed without merging**
